name = "zhuk-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZhukLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false # this project is CC BY 4.0, not Apache 2.0
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "ZhukLean"
