/-
Copyright (c) 2026 Álvaro Begué. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Álvaro Begué
-/
import ZhukLean.Absorbs

/-!
# Zhuk: centrality of the left center

Blueprint Theorem 6.1. For `a` outside the left center `C`, the diagonal pair
`(a, a)` does not lie in the subuniverse of `A × A` generated by
`({a} × C) ∪ (C × C) ∪ (C × {a})`.

## The generator blocks, without sorting them

The blueprint enumerates the generators so that the three blocks appear
consecutively, extracts indices `p ≤ q`, and picks `m` between them. That
apparatus exists only to index a *sorted* enumeration.

Here the variable type of the term **is** the generating set (Mathlib's
`mem_closure_iff_exists_term`), so each variable already knows which block it
lies in and no sorting is needed: the selector is just
`fun g => if g.2 = a then 1 else 0`. Blueprint Lemma 1.20, the block-respecting
enumeration, is not needed at all.
-/

open FirstOrder Language

namespace ZhukLean

variable {L : Language} {A B : Type*} [L.Structure A] [L.Structure B]

/-- The generating set of blueprint Theorem 6.1: the union of the three blocks
`{a} × C`, `C × C` and `C × {a}`. -/
def centralGens (R : L.Substructure (A × B)) (a : A) : Set (A × A) :=
  {p | (p.1 = a ∧ p.2 ∈ leftCenter R) ∨ (p.1 ∈ leftCenter R ∧ p.2 ∈ leftCenter R)
        ∨ (p.1 ∈ leftCenter R ∧ p.2 = a)}

variable {R : L.Substructure (A × B)} {a : A}

/-- First-coordinate valuation on the generating set. Naming it pins the binder type,
which bare `fun g => (g : A × A).1` does not. -/
def gensFst (R : L.Substructure (A × B)) (a : A) : (centralGens R a) → A :=
  fun g => (g : A × A).1

/-- Second-coordinate valuation on the generating set. -/
def gensSnd (R : L.Substructure (A × B)) (a : A) : (centralGens R a) → A :=
  fun g => (g : A × A).2

theorem fst_eq_or_mem {g : A × A} (hg : g ∈ centralGens R a) :
    g.1 = a ∨ g.1 ∈ leftCenter R := by
  rcases hg with ⟨h, _⟩ | ⟨h, _⟩ | ⟨h, _⟩
  · exact Or.inl h
  · exact Or.inr h
  · exact Or.inr h

theorem snd_eq_or_mem {g : A × A} (hg : g ∈ centralGens R a) :
    g.2 = a ∨ g.2 ∈ leftCenter R := by
  rcases hg with ⟨_, h⟩ | ⟨_, h⟩ | ⟨_, h⟩
  · exact Or.inr h
  · exact Or.inr h
  · exact Or.inl h

/-- The three blocks are pairwise disjoint because `a ∉ C`: a generator whose first
coordinate is `a` lies in the first block, so its second coordinate is in `C` and
hence is not `a`. -/
theorem snd_ne_of_fst_eq (ha : a ∉ leftCenter R) {g : A × A} (hg : g ∈ centralGens R a)
    (h1 : g.1 = a) : g.2 ≠ a := by
  rcases hg with ⟨_, h⟩ | ⟨h, _⟩ | ⟨h, _⟩
  · intro hcon; exact ha (hcon ▸ h)
  · exact absurd (h1 ▸ h) ha
  · exact absurd (h1 ▸ h) ha

/-! ## The two claims of blueprint Theorem 6.1 -/

/-- Claim 1: reading the *first* coordinate of the generators. If the term evaluates
to `a` on first coordinates, then it maps any `B`-tuple that is in the neighborhood
of `a` at every generator whose first coordinate is `a` back into that
neighborhood. -/
theorem realize_mem_nbhd_of_fst (t : L.Term (centralGens R a))
    (heq : t.realize (gensFst R a) = a)
    (y : (centralGens R a) → B)
    (hy : ∀ g : centralGens R a, gensFst R a g = a → y g ∈ nbhd R a) :
    t.realize y ∈ nbhd R a := by
  have hpair : ∀ g : centralGens R a, ((gensFst R a g, y g) : A × B) ∈ R := by
    intro g
    rcases fst_eq_or_mem g.2 with h | h
    · rw [show gensFst R a g = a from h]; exact hy g h
    · exact h (y g)
  have hR := t.realize_mem (fun g => ((gensFst R a g, y g) : A × B)) hpair
  rw [realize_prod] at hR
  simpa [heq] using hR

/-- Claim 2: reading the *second* coordinate of the generators. -/
theorem realize_mem_nbhd_of_snd (t : L.Term (centralGens R a))
    (heq : t.realize (gensSnd R a) = a)
    (y : (centralGens R a) → B)
    (hy : ∀ g : centralGens R a, gensSnd R a g = a → y g ∈ nbhd R a) :
    t.realize y ∈ nbhd R a := by
  have hpair : ∀ g : centralGens R a, ((gensSnd R a g, y g) : A × B) ∈ R := by
    intro g
    rcases snd_eq_or_mem g.2 with h | h
    · rw [show gensSnd R a g = a from h]; exact hy g h
    · exact h (y g)
  have hR := t.realize_mem (fun g => ((gensSnd R a g, y g) : A × B)) hpair
  rw [realize_prod] at hR
  simpa [heq] using hR

/-- **Blueprint Theorem 6.1** (Zhuk: centrality of the left center).

Note this needs neither finiteness nor a Taylor term — only that `B` has no
nonempty proper binary absorbing subuniverse. -/
theorem center_central (hA : IsIdempotent L A) (hsd : Subdirect R)
    (hbaf : ∀ N : L.Substructure B, (N : Set B).Nonempty → (N : Set B) ≠ Set.univ →
      ¬ BinAbsorbs L (N : Set B) Set.univ)
    (ha : a ∉ leftCenter R) :
    ((a, a) : A × A) ∉ Substructure.closure L (centralGens R a) := by
  classical
  intro hmem
  obtain ⟨t, ht⟩ := Substructure.mem_closure_iff_exists_term.mp hmem
  rw [realize_prod] at ht
  have hfst : t.realize (gensFst R a) = a := congrArg Prod.fst ht
  have hsnd : t.realize (gensSnd R a) = a := congrArg Prod.snd ht
  -- The selector: send a generator to the second variable exactly when it lies in
  -- the third block. No sorting of the generators is required.
  set μ : (centralGens R a) → Fin 2 := fun g => if gensSnd R a g = a then 1 else 0 with hμ
  have hwit : Witnesses (nbhd R a) (Set.univ : Set B) (t.relabel μ) := by
    intro i z _ hzN
    rw [Term.realize_relabel]
    fin_cases i
    · -- the free variable is `z 0`; `z 1` lies in the neighborhood
      refine realize_mem_nbhd_of_snd t hsnd _ fun g hg => ?_
      have : μ g = 1 := by simp [hμ, hg]
      simpa [Function.comp_def, this] using hzN 1 (by decide)
    · -- the free variable is `z 1`; `z 0` lies in the neighborhood
      refine realize_mem_nbhd_of_fst t hfst _ fun g hg => ?_
      have hne : gensSnd R a g ≠ a := snd_ne_of_fst_eq ha g.2 hg
      have : μ g = 0 := by simp [hμ, hne]
      simpa [Function.comp_def, this] using hzN 0 (by decide)
  have hNne : (nbhd R a).Nonempty := nbhd_nonempty hsd a
  have hNproper : nbhd R a ≠ Set.univ := fun h => ha (nbhd_eq_univ_iff.mp h)
  exact hbaf (nbhdSub hA R a) hNne hNproper ⟨t.relabel μ, hwit⟩

/-! ## Central absorption -/

/-- The two-block generating set of blueprint Definition 6.2: `({a} × C) ∪ (C × {a})`,
without the middle block `C × C` that Theorem 6.1 also allows. -/
def centralPairs {A : Type*} (C : Set A) (a : A) : Set (A × A) :=
  {p | (p.1 = a ∧ p.2 ∈ C) ∨ (p.1 ∈ C ∧ p.2 = a)}

theorem centralPairs_subset_centralGens (R : L.Substructure (A × B)) (a : A) :
    centralPairs (leftCenter R) a ⊆ centralGens R a := by
  rintro p (⟨h1, h2⟩ | ⟨h1, h2⟩)
  · exact Or.inl ⟨h1, h2⟩
  · exact Or.inr (Or.inr ⟨h1, h2⟩)

/-- Blueprint Definition 6.2: `C` centrally absorbs `A`. -/
structure CentrallyAbsorbs (L : Language) {A : Type*} [L.Structure A] (C : Set A) : Prop where
  /-- `C ⊴ A`. -/
  absorbs : Absorbs L C Set.univ
  /-- The diagonal is not generated from the two off-diagonal blocks. -/
  central : ∀ a ∉ C, ((a, a) : A × A) ∉ Substructure.closure L (centralPairs C a)

/-- **Blueprint Corollary 6.3** (Zhuk's center theorem).

If `B` is Taylor and has no nonempty proper binary absorbing subuniverse, then the
left center of a subdirect `R ≤ A × B` centrally absorbs `A`. -/
theorem zhuk_center [Finite B] [Nonempty B] (hA : IsIdempotent L A) (hB : IsIdempotent L B)
    (hsd : Subdirect R) {k : ℕ} {t : L.Term (Fin k)} (T : IsTaylorOn (Set.univ : Set B) t)
    (hbaf : ∀ N : L.Substructure B, (N : Set B).Nonempty → (N : Set B) ≠ Set.univ →
      ¬ BinAbsorbs L (N : Set B) Set.univ) :
    CentrallyAbsorbs L (leftCenter R) where
  absorbs := Absorbs.of_finite (leftCenter_witnesses hA hB hsd T hbaf)
  central a ha hmem :=
    center_central hA hsd hbaf ha
      (Substructure.closure_mono (centralPairs_subset_centralGens R a) hmem)

end ZhukLean
