/-
Copyright (c) 2026 Álvaro Begué. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Álvaro Begué
-/
import ZhukLean.Relational
import ZhukLean.Central

/-!
# The Zhuk–Kozik essential doubling trick

Blueprint Lemma 7.1, specialized to the case its only consumer needs: all factors
are the same finite algebra `A` and all designated subuniverses are the same `C`.

The blueprint's doubled relation is written over
`A₀ × ⋯ × Aₙ × Aₙ × ⋯ × A₀`, with the second half reversed. Essentiality does not
depend on the *order* of the coordinates, so here the doubled index is the sum type
`Fin (n+1) ⊕ Fin (n+1)` and no reversal is needed. Transport to `Fin (2n+2)` is
then handled by `hasEssential_of_essentialOn`, whose base case is exactly a
reindexing.
-/

open FirstOrder Language

namespace ZhukLean

variable {L : Language} {A : Type*} [L.Structure A]

/-! ## The set `B'` -/

/-- Blueprint `β(P)`: the last coordinates of tuples of `P` whose other coordinates
all lie in `C`. -/
def betaSet {n : ℕ} (C : Set A) (R : L.Substructure (Fin (n + 2) → A)) : Set A :=
  {a | ∃ x ∈ R, (∀ r, r ≠ Fin.last (n + 1) → x r ∈ C) ∧ x (Fin.last (n + 1)) = a}

/-- `β(P)` is a subuniverse. -/
def betaSub {n : ℕ} (C : L.Substructure A) (R : L.Substructure (Fin (n + 2) → A)) :
    L.Substructure A where
  carrier := betaSet (C : Set A) R
  fun_mem := by
    intro p f xs hxs
    choose g hgR hgC hglast using hxs
    refine ⟨Structure.funMap f g, R.fun_mem f g hgR, ?_, ?_⟩
    · intro r hr
      exact C.fun_mem f _ fun i => hgC i r hr
    · rw [funMap_pi]
      exact congrArg _ (funext hglast)

@[simp]
theorem coe_betaSub {n : ℕ} (C : L.Substructure A) (R : L.Substructure (Fin (n + 2) → A)) :
    (betaSub C R : Set A) = betaSet (C : Set A) R := rfl

theorem betaSet_nonempty {n : ℕ} {C : Set A} {R : L.Substructure (Fin (n + 2) → A)}
    (h : IsEssential C R) : (betaSet C R).Nonempty := by
  obtain ⟨x, hxR, hxC⟩ := h.witness (Fin.last (n + 1))
  exact ⟨x (Fin.last (n + 1)), x, hxR, hxC, rfl⟩

theorem notMem_of_mem_betaSet {n : ℕ} {C : Set A} {R : L.Substructure (Fin (n + 2) → A)}
    (h : IsEssential C R) {a : A} (ha : a ∈ betaSet C R) : a ∉ C := by
  obtain ⟨x, hxR, hxC, rfl⟩ := ha
  intro hmem
  refine h.no_full x hxR fun r => ?_
  by_cases hr : r = Fin.last (n + 1)
  · exact hr ▸ hmem
  · exact hxC r hr

theorem betaSet_mono {n : ℕ} {C : Set A} {R R' : L.Substructure (Fin (n + 2) → A)}
    (hle : R' ≤ R) : betaSet C R' ⊆ betaSet C R := by
  rintro a ⟨x, hxR, hxC, rfl⟩
  exact ⟨x, hle hxR, hxC, rfl⟩

/-! ## Step 1: the generation property (‡)

Every element of `B'` is generated by `C` together with any other element of `B'`.
This is the statement blueprint Remark 7.2 insists must be proved *before* the
element `b` of Step 2 is fixed, because Step 3 instantiates it twice, the second
time at an element the first instantiation produced. -/

theorem betaSet_subset_closure [Finite A] {n : ℕ} {C : L.Substructure A}
    {R : L.Substructure (Fin (n + 2) → A)} (hR : IsEssential (C : Set A) R)
    (hmin : ∀ R' : L.Substructure (Fin (n + 2) → A), IsEssential (C : Set A) R' →
      (betaSet (C : Set A) R).ncard ≤ (betaSet (C : Set A) R').ncard)
    {b₁ : A} (hb₁ : b₁ ∈ betaSet (C : Set A) R) :
    betaSet (C : Set A) R ⊆ Substructure.closure L ((C : Set A) ∪ {b₁}) := by
  classical
  -- Witnesses for the first `n+1` coordinates; each has its last coordinate in `C`.
  choose x hxR hxC using fun i : Fin (n + 1) => hR.witness i.castSucc
  -- A witness for the last coordinate, with prescribed value `b₁`.
  obtain ⟨y, hyR, hyC, hylast⟩ := hb₁
  set G : Set (Fin (n + 2) → A) := insert y (Set.range x) with hG
  set R'' : L.Substructure (Fin (n + 2) → A) := Substructure.closure L G with hR''
  have hGR : G ⊆ (R : Set (Fin (n + 2) → A)) := by
    rintro _ (rfl | ⟨i, rfl⟩)
    · exact hyR
    · exact hxR i
  have hle : R'' ≤ R := by rw [hR'']; exact Substructure.closure_le.mpr hGR
  -- `R''` is still essential, so it is a competitor in the same minimization.
  have hess : IsEssential (C : Set A) R'' := by
    constructor
    · intro j
      refine Fin.lastCases ?_ ?_ j
      · exact ⟨y, Substructure.subset_closure (Or.inl rfl), hyC⟩
      · intro i
        exact ⟨x i, Substructure.subset_closure (Or.inr ⟨i, rfl⟩), hxC i⟩
    · exact fun z hz => hR.no_full z (hle hz)
  -- Minimality plus containment forces equality of the two `β`s.
  have hsub : betaSet (C : Set A) R'' ⊆ betaSet (C : Set A) R := betaSet_mono hle
  have heq : betaSet (C : Set A) R'' = betaSet (C : Set A) R :=
    (Set.eq_of_subset_of_ncard_le hsub (hmin R'' hess) (Set.toFinite _))
  -- The last coordinate of every generator lies in `C ∪ {b₁}`.
  have hgen : (fun z : Fin (n + 2) → A => z (Fin.last (n + 1))) '' G
      ⊆ (C : Set A) ∪ {b₁} := by
    rintro _ ⟨z, (rfl | ⟨i, rfl⟩), rfl⟩
    · exact Or.inr hylast
    · exact Or.inl (hxC i (Fin.last (n + 1)) (Fin.castSucc_lt_last i).ne')
  -- Hence every last coordinate of `R''` lies in the closure of `C ∪ {b₁}`.
  have hpush : ∀ z ∈ R'', z (Fin.last (n + 1)) ∈ Substructure.closure L ((C : Set A) ∪ {b₁}) := by
    intro z hz
    have hcl : R'' ≤ (Substructure.closure L ((C : Set A) ∪ {b₁})).comap
        (evalHom (Fin.last (n + 1))) := by
      rw [hR'', Substructure.closure_le]
      intro g hg
      exact Substructure.subset_closure (hgen ⟨g, hg, rfl⟩)
    exact hcl hz
  intro a ha
  obtain ⟨z, hzR'', _, rfl⟩ : a ∈ betaSet (C : Set A) R'' := heq ▸ ha
  exact hpush z hzR''

/-- The singleton as a subuniverse, available because `A` is idempotent. -/
def singletonSub (hA : IsIdempotent L A) (b : A) : L.Substructure A where
  carrier := {b}
  fun_mem := fun {_} f => hA.closedUnder_singleton f b

/-! ## Step 3: the linking relation misses `B' × B'`

Blueprint Remark 7.2: this is the only argument in the development that doubles back
on itself. `betaSet_subset_closure` is instantiated twice — at `b'`, and then at the
`b'''` that the first instantiation produced. There is no circularity, because it is
universally quantified and was established before `b` was fixed. -/

theorem linking_disjoint [Finite A] {n : ℕ} {C : L.Substructure A} (hA : IsIdempotent L A)
    (hZ : ∀ a ∉ (C : Set A),
      ((a, a) : A × A) ∉ Substructure.closure L (centralPairs (C : Set A) a))
    {R : L.Substructure (Fin (n + 2) → A)} (hR : IsEssential (C : Set A) R)
    (hmin : ∀ R' : L.Substructure (Fin (n + 2) → A), IsEssential (C : Set A) R' →
      (betaSet (C : Set A) R).ncard ≤ (betaSet (C : Set A) R').ncard)
    {b : A} (hb : b ∈ betaSet (C : Set A) R) :
    ∀ b' ∈ betaSet (C : Set A) R, ∀ b'' ∈ betaSet (C : Set A) R,
      ((b', b'') : A × A) ∉ Substructure.closure L (centralPairs (C : Set A) b) := by
  classical
  intro b' hb' b'' hb'' hpair
  set S : L.Substructure (A × A) := Substructure.closure L (centralPairs (C : Set A) b) with hS
  have hCb : ∀ c ∈ (C : Set A), ((c, b) : A × A) ∈ S := fun c hc =>
    Substructure.subset_closure (Or.inr ⟨hc, rfl⟩)
  have hbC : ∀ c ∈ (C : Set A), ((b, c) : A × A) ∈ S := fun c hc =>
    Substructure.subset_closure (Or.inl ⟨rfl, hc⟩)
  -- `P` collects the elements having an `S`-neighbour in `B'`.
  set P : L.Substructure A := (S ⊓ (betaSub C R).comap sndHom).map fstHom with hP
  have hmemP : ∀ {u w : A}, ((u, w) : A × A) ∈ S → w ∈ betaSet (C : Set A) R → u ∈ P := by
    intro u w hw hwB
    exact ⟨(u, w), ⟨hw, hwB⟩, rfl⟩
  have hCP : (C : Set A) ∪ {b'} ⊆ (P : Set A) := by
    rintro u (hu | rfl)
    · exact hmemP (hCb u hu) hb
    · exact hmemP hpair hb''
  have hbP : b ∈ P :=
    Substructure.closure_le.mpr hCP (betaSet_subset_closure hR hmin hb' hb)
  obtain ⟨q, ⟨hqS, hqB⟩, hq1⟩ := hbP
  set b3 : A := q.2 with hb3
  have hb3B : b3 ∈ betaSet (C : Set A) R := Substructure.mem_comap.mp hqB
  have hbb3 : ((b, b3) : A × A) ∈ S := by
    have : q = (b, b3) := Prod.ext hq1 rfl
    exact this ▸ hqS
  -- `Q` collects the `S`-neighbours of `b`.
  set Q : L.Substructure A := (S ⊓ (singletonSub hA b).comap fstHom).map sndHom with hQ
  have hmemQ : ∀ {w : A}, ((b, w) : A × A) ∈ S → w ∈ Q := fun {w} hw =>
    ⟨(b, w), ⟨hw, Substructure.mem_comap.mpr rfl⟩, rfl⟩
  have hCQ : (C : Set A) ∪ {b3} ⊆ (Q : Set A) := by
    rintro w (hw | rfl)
    · exact hmemQ (hbC w hw)
    · exact hmemQ hbb3
  have hbQ : b ∈ Q :=
    Substructure.closure_le.mpr hCQ (betaSet_subset_closure hR hmin hb3B hb)
  obtain ⟨q', ⟨hq'S, hq'1⟩, hq'2⟩ := hbQ
  have hq'1' : q'.1 = b := Substructure.mem_comap.mp hq'1
  have : q' = (b, b) := Prod.ext hq'1' hq'2
  exact hZ b (notMem_of_mem_betaSet hR hb) (this ▸ hq'S)

/-! ## Step 4: the doubled relation

Indexed by `Fin (n+1) ⊕ Fin (n+1)`. The blueprint reverses the second half; since
essentiality does not depend on the order of coordinates, we do not. -/

/-- Blueprint `R'`: two tuples of `R` with their last coordinates linked by `S`. -/
def doubled {n : ℕ} (R : L.Substructure (Fin (n + 2) → A)) (S : L.Substructure (A × A)) :
    L.Substructure ((Fin (n + 1) ⊕ Fin (n + 1)) → A) where
  carrier := {z | ∃ u v : A, Fin.snoc (z ∘ Sum.inl) u ∈ R ∧ Fin.snoc (z ∘ Sum.inr) v ∈ R
      ∧ ((u, v) : A × A) ∈ S}
  fun_mem := by
    intro p f zs hzs
    choose u v hu hv huv using hzs
    have hl : (Structure.funMap f zs) ∘ Sum.inl
        = Structure.funMap f (fun i => zs i ∘ Sum.inl) := by funext r; rfl
    have hr : (Structure.funMap f zs) ∘ Sum.inr
        = Structure.funMap f (fun i => zs i ∘ Sum.inr) := by funext r; rfl
    refine ⟨Structure.funMap f u, Structure.funMap f v, ?_, ?_, ?_⟩
    · rw [hl, snoc_funMap]; exact R.fun_mem f _ hu
    · rw [hr, snoc_funMap]; exact R.fun_mem f _ hv
    · exact S.fun_mem f (fun i => ((u i, v i) : A × A)) huv

/-- **Blueprint Lemma 7.1** (the Zhuk–Kozik doubling trick), in the form its consumer
needs: a `C`-essential relation of arity `n+2` yields one of arity `2n+2`. -/
theorem hasEssential_doubled [Finite A] {n : ℕ} {C : L.Substructure A} (hA : IsIdempotent L A)
    (hZ : ∀ a ∉ (C : Set A),
      ((a, a) : A × A) ∉ Substructure.closure L (centralPairs (C : Set A) a))
    (h : HasEssential L (C : Set A) (n + 2)) :
    HasEssential L (C : Set A) (n + 1 + (n + 1)) := by
  classical
  -- Step 0: choose a relation minimizing `|B'|`.
  have hex : ∃ k, ∃ R : L.Substructure (Fin (n + 2) → A),
      IsEssential (C : Set A) R ∧ (betaSet (C : Set A) R).ncard = k := by
    obtain ⟨R, hR⟩ := h; exact ⟨_, R, hR, rfl⟩
  obtain ⟨R, hR, hRk⟩ := Nat.find_spec hex
  have hmin : ∀ R' : L.Substructure (Fin (n + 2) → A), IsEssential (C : Set A) R' →
      (betaSet (C : Set A) R).ncard ≤ (betaSet (C : Set A) R').ncard := by
    intro R' hR'
    rw [hRk]
    exact Nat.find_le ⟨R', hR', rfl⟩
  obtain ⟨b, hb⟩ := betaSet_nonempty hR
  set S : L.Substructure (A × A) := Substructure.closure L (centralPairs (C : Set A) b) with hS
  obtain ⟨y, hyR, hyC, hylast⟩ := hb
  have hbmem : b ∈ betaSet (C : Set A) R := ⟨y, hyR, hyC, hylast⟩
  -- Apply regrouping to the doubled relation, with the block function a bijection.
  refine hasEssential_of_essentialOn (Finset.univ).card Finset.univ
    (finSumFinEquiv : (Fin (n + 1) ⊕ Fin (n + 1)) ≃ Fin (n + 1 + (n + 1))) (doubled R S) rfl ?_
  -- The witness statement, proved for an arbitrary free coordinate and then
  -- instantiated at `finSumFinEquiv.symm j`.
  have key : ∀ s₀ : Fin (n + 1) ⊕ Fin (n + 1),
      ∃ z ∈ doubled R S, ∀ s', s' ≠ s₀ → z s' ∈ (C : Set A) := by
    intro s₀
    rcases s₀ with i | i
    · obtain ⟨x, hxR, hxC⟩ := hR.witness i.castSucc
      have hxlast : x (Fin.last (n + 1)) ∈ (C : Set A) := hxC _ (Fin.castSucc_lt_last i).ne'
      refine ⟨Sum.elim (x ∘ Fin.castSucc) (y ∘ Fin.castSucc),
        ⟨x (Fin.last (n + 1)), b, ?_, ?_, ?_⟩, ?_⟩
      · rw [show (Sum.elim (x ∘ Fin.castSucc) (y ∘ Fin.castSucc)) ∘ Sum.inl = Fin.init x from rfl,
          Fin.snoc_init_self]
        exact hxR
      · rw [show (Sum.elim (x ∘ Fin.castSucc) (y ∘ Fin.castSucc)) ∘ Sum.inr = Fin.init y from rfl,
          ← hylast, Fin.snoc_init_self]
        exact hyR
      · exact Substructure.subset_closure (Or.inr ⟨hxlast, rfl⟩)
      · rintro (i' | i') hne
        · exact hxC i'.castSucc fun hcon => hne (by rw [Fin.castSucc_inj.mp hcon])
        · exact hyC i'.castSucc (Fin.castSucc_lt_last i').ne
    · obtain ⟨x, hxR, hxC⟩ := hR.witness i.castSucc
      have hxlast : x (Fin.last (n + 1)) ∈ (C : Set A) := hxC _ (Fin.castSucc_lt_last i).ne'
      refine ⟨Sum.elim (y ∘ Fin.castSucc) (x ∘ Fin.castSucc),
        ⟨b, x (Fin.last (n + 1)), ?_, ?_, ?_⟩, ?_⟩
      · rw [show (Sum.elim (y ∘ Fin.castSucc) (x ∘ Fin.castSucc)) ∘ Sum.inl = Fin.init y from rfl,
          ← hylast, Fin.snoc_init_self]
        exact hyR
      · rw [show (Sum.elim (y ∘ Fin.castSucc) (x ∘ Fin.castSucc)) ∘ Sum.inr = Fin.init x from rfl,
          Fin.snoc_init_self]
        exact hxR
      · exact Substructure.subset_closure (Or.inl ⟨rfl, hxlast⟩)
      · rintro (i' | i') hne
        · exact hyC i'.castSucc (Fin.castSucc_lt_last i').ne
        · exact hxC i'.castSucc fun hcon => hne (by rw [Fin.castSucc_inj.mp hcon])
  constructor
  · -- (B1): instantiate `key` at the preimage of `j`.
    intro j
    obtain ⟨z, hz, hzC⟩ := key (finSumFinEquiv.symm j)
    exact ⟨z, hz, fun s' _ hne => hzC s' fun hcon => hne (by rw [hcon]; simp)⟩
  · -- (B2)
    rintro z ⟨u, v, hu, hv, huv⟩ hall
    have hubeta : u ∈ betaSet (C : Set A) R := by
      refine ⟨_, hu, fun r hr => ?_, ?_⟩
      · obtain ⟨r', rfl⟩ := Fin.exists_castSucc_eq.mpr hr
        simpa using hall (Sum.inl r') (Finset.mem_univ _)
      · simp
    have hvbeta : v ∈ betaSet (C : Set A) R := by
      refine ⟨_, hv, fun r hr => ?_, ?_⟩
      · obtain ⟨r', rfl⟩ := Fin.exists_castSucc_eq.mpr hr
        simpa using hall (Sum.inr r') (Finset.mem_univ _)
      · simp
    exact linking_disjoint hA hZ hR hmin hbmem u hubeta v hvbeta huv

end ZhukLean
